swagger: "2.0"
info:
  description: "This is the configuration for the ArtFactor API"
  version: "1.0.0"
  title: "Swagger ArtFactor"
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /fact:
    get:
      operationId: services.fact.read_true_false_false
      tags:
        - Fact
      summary: Read true random fact(s) from ArtOntolgy
      description: Read true random fact(s) from ArtOntolgy
      parameters:
          - in: query
            name: subjects
            type: array
            items:
              type: string
            required: False
            description: List of URIs of subjects
      responses:
        200:
          description: Successfully read fact list operation
          schema:
            type: array
            items:
                type: array
                items:
                  properties:
                    resource:
                      type: string
                    subject:
                      type: string
                    predicate:
                      type: string
                    object:
                      type: string
                    sentence:
                      type: string
                    trueFact:
                      type: boolean
  /answer:
    get:
      operationId: services.answer.log_answer
      tags:
        - Answer
      summary: Logs for each user if answered right or wrong
      parameters:
        - in: query
          name: userId
          type: integer
          required: true
        - in: query
          name: selectedTrueFact
          type: boolean
          required: true
      responses:
        '201':
          description: Logged
  /search:
    get:
      operationId: services.elastic.search
      tags:
        - ElasticSearch
      summary: Returns fuzzy result matching query from Elastic index
      description: Returns fuzzy result matching query from Elastic index
      parameters:
          - in: query
            name: fuzzy
            type: string
            description: String to fuzzy on Elastic Index
            required: true
      responses:
        200:
          description: Found following results matching fuzzyquery
          schema:
            type: array
            items:
                type: array
                items:
                  properties:
                    class:
                      type: string
                    uri:
                      type: string
                    label:
                      type: string
